name: "Deploy to github pages"
description: "Build and deploy assets to github pages"
on:
  push: 
    branches: ['main']

jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Download files from the current repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      
      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Archive artifact
        shell: sh
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
          echo ::endgroup::
        env:
          INPUT_PATH: build

      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: scorescribe
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          if-no-files-found: error
